# Generated by Django 4.1 on 2022-09-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tables",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("len_person", models.IntegerField()),
                ("max_person", models.IntegerField()),
                ("level", models.IntegerField()),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
